const cards_data = [
  {
    id: 502356,
    original_title: "The Super Mario Bros. Movie",
    title: "The Super Mario Bros. Movie",
    overview: "While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.",
    backdrop_path: "/iJQIbOPm81fPEGKt5BPuZmfnA54.jpg",
    poster_path: "/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
    release_date: "2023-04-05",
    vote_average: 7.5,
    popularity: 6572.614,
    genre_ids: [16, 12, 10751, 14, 35],
  },
  {
    id: 594767,
    original_title: "Shazam! Fury of the Gods",
    title: "Shazam! Fury of the Gods",
    overview: "Billy Batson and his foster siblings, who transform into superheroes by saying \"Shazam!\", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world.",
    backdrop_path: "/nDxJJyA5giRhXx96q1sWbOUjMBI.jpg",
    poster_path: "/2VK4d3mqqTc7LVZLnLPeRiPaJ71.jpg",
    release_date: "2023-03-15",
    vote_average: 6.9,
    popularity: 4274.232,
    genre_ids: [28, 35, 14],
  },
  {
    id: 713704,
    original_title: "Evil Dead Rise",
    title: "Evil Dead Rise",
    overview: "Two sisters find an ancient vinyl that gives birth to bloodthirsty demons that run amok in a Los Angeles apartment building and thrusts them into a primal battle for survival as they face the most nightmarish version of family imaginable.",
    backdrop_path: "/7bWxAsNPv9CXHOhZbJVlj2KxgfP.jpg",
    poster_path: "/mIBCtPvKZQlxubxKMeViO2UrP3q.jpg",
    release_date: "2023-04-12",
    vote_average: 7.0,
    popularity: 1696.367,
    genre_ids: [27, 53],
  },
  {
    id: 315162,
    original_title: "Puss in Boots: The Last Wish",
    title: "Puss in Boots: The Last Wish",
    overview: "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    backdrop_path: "/ouB7hwclG7QI3INoYJHaZL4vOaa.jpg",
    poster_path: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    release_date: "2022-12-07",
    vote_average: 8.3,
    popularity: 1347.259,
    genre_ids: [16, 10751, 14, 12, 35, 18],
  },
  {
    id: 603692,
    original_title: "John Wick: Chapter 4",
    title: "John Wick: Chapter 4",
    overview: "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
    backdrop_path: "/h8gHn0OzBoaefsYseUByqsmEDMY.jpg",
    poster_path: "/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    release_date: "2023-03-22",
    vote_average: 8.0,
    popularity: 1320.735,
    genre_ids: [28, 53, 80],
  },
  {
    id: 804150,
    original_title: "Cocaine Bear",
    title: "Cocaine Bear",
    overview: "Inspired by a true story, an oddball group of cops, criminals, tourists and teens converge in a Georgia forest where a 500-pound black bear goes on a murderous rampage after unintentionally ingesting cocaine.",
    backdrop_path: "/a2tys4sD7xzVaogPntGsT1ypVoT.jpg",
    poster_path: "/gOnmaxHo0412UVr1QM5Nekv1xPi.jpg",
    release_date: "2023-02-22",
    vote_average: 6.4,
    popularity: 1175.491,
    genre_ids: [53, 35, 80],
  },
  {
    id: 700391,
    original_title: "65",
    title: "65",
    overview: "65 million years ago, the only 2 survivors of a spaceship from Somaris that crash-landed on Earth must fend off dinosaurs and reach the escape vessel in time before an imminent asteroid strike threatens to destroy the planet.",
    backdrop_path: "/eSVu1FvGPy86TDo4hQbpuHx55DJ.jpg",
    poster_path: "/rzRb63TldOKdKydCvWJM8B6EkPM.jpg",
    release_date: "2023-03-02",
    vote_average: 6.3,
    popularity: 1077.09,
    genre_ids: [878, 12, 53, 28],
  },
  {
    id: 758323,
    original_title: "The Pope's Exorcist",
    title: "The Pope's Exorcist",
    overview: "Father Gabriele Amorth, Chief Exorcist of the Vatican, investigates a young boy's terrifying possession and ends up uncovering a centuries-old conspiracy the Vatican has desperately tried to keep hidden.",
    backdrop_path: "/5Y5pz0NX7SZS9036I733F7uNcwK.jpg",
    poster_path: "/9JBEPLTPSm0d1mbEcLxULjJq9Eh.jpg",
    release_date: "2023-04-05",
    vote_average: 6.5,
    popularity: 1073.229,
    genre_ids: [27, 53],
  },
  {
    id: 868759,
    original_title: "Ghosted",
    title: "Ghosted",
    overview: "Salt-of-the-earth Cole falls head over heels for enigmatic Sadie — but then makes the shocking discovery that she's a secret agent. Before they can decide on a second date, Cole and Sadie are swept away on an international adventure to save the world.",
    backdrop_path: "/b9UCfDzwiWw7mIFsIQR9ZJUeh7q.jpg",
    poster_path: "/liLN69YgoovHVgmlHJ876PKi5Yi.jpg",
    release_date: "2023-04-21",
    vote_average: 7.3,
    popularity: 867.762,
    genre_ids: [10749, 28, 35],
  },
  {
    id: 934433,
    original_title: "Scream VI",
    title: "Scream VI",
    overview: "Following the latest Ghostface killings, the four survivors leave Woodsboro behind and start a fresh chapter.",
    backdrop_path: "/44immBwzhDVyjn87b3x3l9mlhAD.jpg",
    poster_path: "/wDWwtvkRRlgTiUr6TyLSMX8FCuZ.jpg",
    release_date: "2023-03-08",
    vote_average: 7.4,
    popularity: 853.917,
    genre_ids: [27, 9648, 53],
  },
  {
    id: 536554,
    original_title: "M3GAN",
    title: "M3GAN",
    overview: "A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll's programming works too well, she becomes overprotective of her new friend with terrifying results.",
    backdrop_path: "/dlrWhn0G3AtxYUx2D9P2bmzcsvF.jpg",
    poster_path: "/d9nBoowhjiiYc4FBNtQkPY7c11H.jpg",
    release_date: "2022-12-28",
    vote_average: 7.4,
    popularity: 715.958,
    genre_ids: [878, 27, 35],
  },
  {
    id: 631842,
    original_title: "Knock at the Cabin",
    title: "Knock at the Cabin",
    overview: "While vacationing at a remote cabin, a young girl and her two fathers are taken hostage by four armed strangers who demand that the family make an unthinkable choice to avert the apocalypse.",
    backdrop_path: "/aHcWyh0n4YbBy9gxYCDlgsNVS3M.jpg",
    poster_path: "/dm06L9pxDOL9jNSK4Cb6y139rrG.jpg",
    release_date: "2023-02-01",
    vote_average: 6.4,
    popularity: 528.208,
    genre_ids: [27, 9648, 53],
  },
  {
    id: 980078,
    original_title: "Winnie the Pooh: Blood and Honey",
    title: "Winnie the Pooh: Blood and Honey",
    overview: "Christopher Robin is headed off to college and he has abandoned his old friends, Pooh and Piglet, which then leads to the duo embracing their inner monsters.",
    backdrop_path: "/wD2kUCX1Bb6oeIb2uz7kbdfLP6k.jpg",
    poster_path: "/ewF3IlGscc7FjgGEPcQvZsAsgAW.jpg",
    release_date: "2023-01-27",
    vote_average: 5.8,
    popularity: 690.338,
    genre_ids: [27, 53],
  },
  {
    id: 840326,
    original_title: "Sisu",
    title: "Sisu",
    overview: "Deep in the wilderness of Lapland, Aatami Korpi is searching for gold but after he stumbles upon Nazi patrol, a breathtaking and gold-hungry chase through the destroyed and mined Lapland wilderness begins.",
    backdrop_path: "/94TIUEhuwv8PhdIADEvSuwPljS5.jpg",
    poster_path: "/dHx5yuBb05U9vNaNhIBD7jWyxPk.jpg",
    release_date: "2023-01-27",
    vote_average: 6.9,
    popularity: 364.899,
    genre_ids: [10752, 28],
  },
];

export default cards_data;