const popular_data = [
  {
    id: 640146,
    original_title: "Ant-Man and the Wasp: Quantumania",
    title: "Ant-Man and the Wasp: Quantumania",
    overview: "Super-Hero partners Scott Lang and Hope van Dyne, along with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
    backdrop_path: "/gMJngTNfaqCSCqGD4y8lVMZXKDn.jpg",
    poster_path: "/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg",
    release_date: "2023-02-15",
    vote_average: 6.5,
    popularity: 8567.865,
    genre_ids: [28, 12, 878],
  },
  {
    id: 502356,
    original_title: "The Super Mario Bros. Movie",
    title: "The Super Mario Bros. Movie",
    overview: "While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world.",
    backdrop_path: "/iJQIbOPm81fPEGKt5BPuZmfnA54.jpg",
    poster_path: "/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
    release_date: "2023-04-05",
    vote_average: 7.5,
    popularity: 6572.614,
    genre_ids: [16, 12, 10751, 14, 35],
  },
  {
    id: 594767,
    original_title: "Shazam! Fury of the Gods",
    title: "Shazam! Fury of the Gods",
    overview: "Billy Batson and his foster siblings, who transform into superheroes by saying \"Shazam!\", are forced to get back into action and fight the Daughters of Atlas.",
    backdrop_path: "/nDxJJyA5giRhXx96q1sWbOUjMBI.jpg",
    poster_path: "/2VK4d3mqqTc7LVZLnLPeRiPaJ71.jpg",
    release_date: "2023-03-15",
    vote_average: 6.9,
    popularity: 4274.232,
    genre_ids: [28, 35, 14],
  },
  {
    id: 76600,
    original_title: "Avatar: The Way of Water",
    title: "Avatar: The Way of Water",
    overview: "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe.",
    backdrop_path: "/ovM06PdF3M8wvKb06i4sjW3xoww.jpg",
    poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    release_date: "2022-12-14",
    vote_average: 7.7,
    popularity: 3365.913,
    genre_ids: [878, 12, 28],
  },
  {
    id: 948713,
    original_title: "The Last Kingdom: Seven Kings Must Die",
    title: "The Last Kingdom: Seven Kings Must Die",
    overview: "In the wake of King Edward's death, Uhtred of Bebbanburg and his comrades adventure across a fractured kingdom in the hopes of uniting England at last.",
    backdrop_path: "/xwA90BwZXTh8ke3CVsQlj8EOkFr.jpg",
    poster_path: "/7yyFEsuaLGTPul5UkHc5BhXnQ0k.jpg",
    release_date: "2023-04-14",
    vote_average: 7.4,
    popularity: 3119.049,
    genre_ids: [28, 12, 36, 18, 10752],
  },
  {
    id: 677179,
    original_title: "Creed III",
    title: "Creed III",
    overview: "After dominating the boxing world, Adonis Creed has been thriving in both his career and family life. When a childhood friend and former boxing prodigy resurfaces after serving a long sentence in prison, he is eager to prove that he deserves his shot in the ring.",
    backdrop_path: "/5i6SjyDbDWqyun8klUuCxrlFbyw.jpg",
    poster_path: "/cvsXj3I9Q2iyyIo95AecSd1tad7.jpg",
    release_date: "2023-03-01",
    vote_average: 7.3,
    popularity: 2856.222,
    genre_ids: [18, 28],
  },
  {
    id: 638974,
    original_title: "Murder Mystery 2",
    title: "Murder Mystery 2",
    overview: "After starting their own detective agency, Nick and Audrey Spitz land a career-making case when their billionaire pal is kidnapped from his wedding.",
    backdrop_path: "/bT3IpP7OopgiVuy6HCPOWLuaFAd.jpg",
    poster_path: "/s1VzVhXlqsevi8zeCMG9A16nEUf.jpg",
    release_date: "2023-03-28",
    vote_average: 6.5,
    popularity: 1879.655,
    genre_ids: [35, 9648, 28],
  },
  {
    id: 713704,
    original_title: "Evil Dead Rise",
    title: "Evil Dead Rise",
    overview: "Two sisters find an ancient vinyl that gives birth to bloodthirsty demons that run amok in a Los Angeles apartment building.",
    backdrop_path: "/7bWxAsNPv9CXHOhZbJVlj2KxgfP.jpg",
    poster_path: "/mIBCtPvKZQlxubxKMeViO2UrP3q.jpg",
    release_date: "2023-04-12",
    vote_average: 7.0,
    popularity: 1696.367,
    genre_ids: [27, 53],
  },
  {
    id: 315162,
    original_title: "Puss in Boots: The Last Wish",
    title: "Puss in Boots: The Last Wish",
    overview: "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left.",
    backdrop_path: "/ouB7hwclG7QI3INoYJHaZL4vOaa.jpg",
    poster_path: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    release_date: "2022-12-07",
    vote_average: 8.3,
    popularity: 1347.259,
    genre_ids: [16, 10751, 14, 12, 35, 18],
  },
  {
    id: 603692,
    original_title: "John Wick: Chapter 4",
    title: "John Wick: Chapter 4",
    overview: "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table.",
    backdrop_path: "/h8gHn0OzBoaefsYseUByqsmEDMY.jpg",
    poster_path: "/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    release_date: "2023-03-22",
    vote_average: 8.0,
    popularity: 1320.735,
    genre_ids: [28, 53, 80],
  },
  {
    id: 804150,
    original_title: "Cocaine Bear",
    title: "Cocaine Bear",
    overview: "Inspired by a true story, an oddball group of cops, criminals, tourists and teens converge in a Georgia forest where a 500-pound black bear goes on a murderous rampage.",
    backdrop_path: "/a2tys4sD7xzVaogPntGsT1ypVoT.jpg",
    poster_path: "/gOnmaxHo0412UVr1QM5Nekv1xPi.jpg",
    release_date: "2023-02-22",
    vote_average: 6.4,
    popularity: 1175.491,
    genre_ids: [53, 35, 80],
  },
  {
    id: 849869,
    original_title: "Kill Boksoon",
    title: "Kill Boksoon",
    overview: "At work, she's a renowned assassin. At home, she's a single mom to a teenage daughter. Killing? That's easy. It's parenting that's the hard part.",
    backdrop_path: "/tYcmm8XtzRdcT6kliCbHuWwLCwB.jpg",
    poster_path: "/taYgn3RRpCGlTGdaGQvnSIOzXFy.jpg",
    release_date: "2023-02-17",
    vote_average: 6.8,
    popularity: 958.517,
    genre_ids: [28, 80, 53],
  },
];

export default popular_data;
