const top_rated_data = [
  {
    id: 238,
    original_title: "The Godfather",
    title: "The Godfather",
    overview: "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch Vito Corleone barely survives an attempt on his life, his youngest son Michael steps in to take care of the would-be killers.",
    backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    release_date: "1972-03-14",
    vote_average: 8.7,
    popularity: 100.932,
    genre_ids: [18, 80],
  },
  {
    id: 278,
    original_title: "The Shawshank Redemption",
    title: "The Shawshank Redemption",
    overview: "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden.",
    backdrop_path: "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    poster_path: "/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    release_date: "1994-09-23",
    vote_average: 8.7,
    popularity: 98.25,
    genre_ids: [18, 80],
  },
  {
    id: 240,
    original_title: "The Godfather Part II",
    title: "The Godfather Part II",
    overview: "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    backdrop_path: "/kGzFbGhp99zva6oZODW5atUtnqi.jpg",
    poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
    release_date: "1974-12-20",
    vote_average: 8.6,
    popularity: 57.533,
    genre_ids: [18, 80],
  },
  {
    id: 424,
    original_title: "Schindler's List",
    title: "Schindler's List",
    overview: "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    backdrop_path: "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
    poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    release_date: "1993-12-15",
    vote_average: 8.6,
    popularity: 51.98,
    genre_ids: [18, 36, 10752],
  },
  {
    id: 129,
    original_title: "Spirited Away",
    title: "Spirited Away",
    overview: "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    backdrop_path: "/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg",
    poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    release_date: "2001-07-20",
    vote_average: 8.5,
    popularity: 85.662,
    genre_ids: [16, 10751, 14],
  },
  {
    id: 496243,
    original_title: "Parasite",
    title: "Parasite",
    overview: "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    backdrop_path: "/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
    poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    release_date: "2019-05-30",
    vote_average: 8.5,
    popularity: 72.256,
    genre_ids: [35, 53, 18],
  },
  {
    id: 155,
    original_title: "The Dark Knight",
    title: "The Dark Knight",
    overview: "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague Gotham City.",
    backdrop_path: "/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    release_date: "2008-07-14",
    vote_average: 8.5,
    popularity: 83.151,
    genre_ids: [18, 28, 80, 53],
  },
  {
    id: 372058,
    original_title: "Your Name.",
    title: "Your Name.",
    overview: "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
    backdrop_path: "/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg",
    poster_path: "/q719jXXEzOoYaps6babgKnONONX.jpg",
    release_date: "2016-08-26",
    vote_average: 8.5,
    popularity: 94.963,
    genre_ids: [10749, 16, 18],
  },
  {
    id: 497,
    original_title: "The Green Mile",
    title: "The Green Mile",
    overview: "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments.",
    backdrop_path: "/vxJ08SvwomfKbpboCWynC3uqUg4.jpg",
    poster_path: "/o0lO84GI7qrG6XFvtsPOSV7CTNa.jpg",
    release_date: "1999-12-10",
    vote_average: 8.5,
    popularity: 58.199,
    genre_ids: [14, 18, 80],
  },
  {
    id: 680,
    original_title: "Pulp Fiction",
    title: "Pulp Fiction",
    overview: "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper.",
    backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_date: "1994-09-10",
    vote_average: 8.5,
    popularity: 68.574,
    genre_ids: [53, 80],
  },
  {
    id: 13,
    original_title: "Forrest Gump",
    title: "Forrest Gump",
    overview: "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do.",
    backdrop_path: "/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg",
    poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    release_date: "1994-06-23",
    vote_average: 8.5,
    popularity: 62.225,
    genre_ids: [35, 18, 10749],
  },
  {
    id: 122,
    original_title: "The Lord of the Rings: The Return of the King",
    title: "The Lord of the Rings: The Return of the King",
    overview: "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces.",
    backdrop_path: "/9DeGfFIqjph5CBFVQrD6wv9S7rR.jpg",
    poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    release_date: "2003-12-01",
    vote_average: 8.5,
    popularity: 70.315,
    genre_ids: [12, 14, 28],
  },
  {
    id: 429,
    original_title: "The Good, the Bad and the Ugly",
    title: "The Good, the Bad and the Ugly",
    overview: "While the Civil War rages on between the Union and the Confederacy, three men comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
    backdrop_path: "/eoCSp75lxatmIa6aGqfnzwtbttd.jpg",
    poster_path: "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
    release_date: "1966-12-23",
    vote_average: 8.5,
    popularity: 56.064,
    genre_ids: [37],
  },
  {
    id: 769,
    original_title: "GoodFellas",
    title: "GoodFellas",
    overview: "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family.",
    backdrop_path: "/sw7mordbZxgITU877yTpZCud90M.jpg",
    poster_path: "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
    release_date: "1990-09-12",
    vote_average: 8.5,
    popularity: 39.718,
    genre_ids: [18, 80],
  },
];

export default top_rated_data;
