const upcoming_data = [
  {
    id: 385687,
    original_title: "Fast X",
    title: "Fast X",
    overview: "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path.",
    backdrop_path: "/fI5RsaM0NSU6TqztRhA2pal5ezv.jpg",
    poster_path: "/jwMMQR69Xz9AYtX4u2uYJgfAAev.jpg",
    release_date: "2023-05-17",
    vote_average: 7.2,
    popularity: 524.606,
    genre_ids: [28, 80, 53],
  },
  {
    id: 447365,
    original_title: "Guardians of the Galaxy Volume 3",
    title: "Guardians of the Galaxy Volume 3",
    overview: "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own.",
    backdrop_path: "/7TUp4uKIaX9c2TAZLPwjty5A0EP.jpg",
    poster_path: "/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
    release_date: "2023-05-03",
    vote_average: 8.2,
    popularity: 239.132,
    genre_ids: [878, 12, 28],
  },
  {
    id: 447277,
    original_title: "The Little Mermaid",
    title: "The Little Mermaid",
    overview: "The youngest of King Triton's daughters, and the most defiant, Ariel longs to find out more about the world beyond the sea, and while visiting the surface, falls for the dashing Prince Eric.",
    backdrop_path: "/3phD5uW41TZ8RavH9xjQv661MPw.jpg",
    poster_path: "/ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg",
    release_date: "2023-05-18",
    vote_average: 7.0,
    popularity: 246.482,
    genre_ids: [12, 10751, 14, 10749],
  },
  {
    id: 713704,
    original_title: "Evil Dead Rise",
    title: "Evil Dead Rise",
    overview: "Two sisters find an ancient vinyl that gives birth to bloodthirsty demons that run amok in a Los Angeles apartment building.",
    backdrop_path: "/7bWxAsNPv9CXHOhZbJVlj2KxgfP.jpg",
    poster_path: "/mIBCtPvKZQlxubxKMeViO2UrP3q.jpg",
    release_date: "2023-04-12",
    vote_average: 7.0,
    popularity: 1696.367,
    genre_ids: [27, 53],
  },
  {
    id: 758323,
    original_title: "The Pope's Exorcist",
    title: "The Pope's Exorcist",
    overview: "Father Gabriele Amorth, Chief Exorcist of the Vatican, investigates a young boy's terrifying possession and ends up uncovering a centuries-old conspiracy.",
    backdrop_path: "/5Y5pz0NX7SZS9036I733F7uNcwK.jpg",
    poster_path: "/9JBEPLTPSm0d1mbEcLxULjJq9Eh.jpg",
    release_date: "2023-04-05",
    vote_average: 6.5,
    popularity: 1073.229,
    genre_ids: [27, 53],
  },
  {
    id: 840326,
    original_title: "Sisu",
    title: "Sisu",
    overview: "Deep in the wilderness of Lapland, Aatami Korpi is searching for gold but after he stumbles upon Nazi patrol, a breathtaking chase through destroyed and mined wilderness begins.",
    backdrop_path: "/94TIUEhuwv8PhdIADEvSuwPljS5.jpg",
    poster_path: "/dHx5yuBb05U9vNaNhIBD7jWyxPk.jpg",
    release_date: "2023-01-27",
    vote_average: 6.9,
    popularity: 364.899,
    genre_ids: [10752, 28],
  },
  {
    id: 980078,
    original_title: "Winnie the Pooh: Blood and Honey",
    title: "Winnie the Pooh: Blood and Honey",
    overview: "Christopher Robin is headed off to college and he has abandoned his old friends, Pooh and Piglet, which then leads to the duo embracing their inner monsters.",
    backdrop_path: "/wD2kUCX1Bb6oeIb2uz7kbdfLP6k.jpg",
    poster_path: "/ewF3IlGscc7FjgGEPcQvZsAsgAW.jpg",
    release_date: "2023-01-27",
    vote_average: 5.8,
    popularity: 690.338,
    genre_ids: [27, 53],
  },
  {
    id: 649609,
    original_title: "Renfield",
    title: "Renfield",
    overview: "Having grown sick and tired of his centuries as Dracula's lackey, Renfield finds a new lease on life when he falls for feisty traffic cop Rebecca Quincy.",
    backdrop_path: "/kfKW0HBObLAd4Lj27XX5QoLWmGe.jpg",
    poster_path: "/p6yUjhvNGQpFZilKwOKbxQ1eHlo.jpg",
    release_date: "2023-04-07",
    vote_average: 6.8,
    popularity: 106.081,
    genre_ids: [35, 27, 14],
  },
  {
    id: 842675,
    original_title: "The Wandering Earth II",
    title: "The Wandering Earth II",
    overview: "Humans built huge engines on the surface of the earth to find a new home. But the road to the universe is perilous. In order to save earth, young people once again have to start a race against time.",
    backdrop_path: "/qElNES0sHVQcbzvGrTx7ccpGzij.jpg",
    poster_path: "/pR858ihc6Ls9xohpdRJVjV787ml.jpg",
    release_date: "2023-01-22",
    vote_average: 7.6,
    popularity: 99.801,
    genre_ids: [878, 28, 18],
  },
];

export default upcoming_data;
